// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjJT3T2aD3mCdIYGqAuWskgswrVL05eq8',
    appId: '1:861525505716:web:a2f4ce69616e8397a5c9e1',
    messagingSenderId: '861525505716',
    projectId: 'academic-archival-system',
    authDomain: 'academic-archival-system.firebaseapp.com',
    databaseURL: 'https://academic-archival-system-default-rtdb.firebaseio.com',
    storageBucket: 'academic-archival-system.firebasestorage.app',
    measurementId: 'G-JF2LNTFE3P',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIp_UNPK1lwPtj2isryeTlo7VZEC1O3l4',
    appId: '1:861525505716:ios:19934b6b085bc220a5c9e1',
    messagingSenderId: '861525505716',
    projectId: 'academic-archival-system',
    databaseURL: 'https://academic-archival-system-default-rtdb.firebaseio.com',
    storageBucket: 'academic-archival-system.firebasestorage.app',
    iosBundleId: 'com.example.ocrDocumentScannerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIp_UNPK1lwPtj2isryeTlo7VZEC1O3l4',
    appId: '1:861525505716:ios:19934b6b085bc220a5c9e1',
    messagingSenderId: '861525505716',
    projectId: 'academic-archival-system',
    databaseURL: 'https://academic-archival-system-default-rtdb.firebaseio.com',
    storageBucket: 'academic-archival-system.firebasestorage.app',
    iosBundleId: 'com.example.ocrDocumentScannerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjJT3T2aD3mCdIYGqAuWskgswrVL05eq8',
    appId: '1:861525505716:web:348c6d33d7ad79d4a5c9e1',
    messagingSenderId: '861525505716',
    projectId: 'academic-archival-system',
    authDomain: 'academic-archival-system.firebaseapp.com',
    databaseURL: 'https://academic-archival-system-default-rtdb.firebaseio.com',
    storageBucket: 'academic-archival-system.firebasestorage.app',
    measurementId: 'G-J6F4L0M2MS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBf_zIENEUG7BNUUxokLQa3AQv-t1OJthI',
    appId: '1:861525505716:android:ddcd7b4c52540a9fa5c9e1',
    messagingSenderId: '861525505716',
    projectId: 'academic-archival-system',
    databaseURL: 'https://academic-archival-system-default-rtdb.firebaseio.com',
    storageBucket: 'academic-archival-system.firebasestorage.app',
  );

}